# Generated by Django 4.1.5 on 2023-02-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Объект договора')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectByDogovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Объект договора')),
                ('dogovors', models.ManyToManyField(related_name='dogovors', to='dogovor_online.dogovor', verbose_name='Договоры')),
            ],
        ),
    ]
