# Generated by Django 4.1.5 on 2023-02-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogovor_online', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogovor',
            options={'verbose_name': 'Договор', 'verbose_name_plural': 'Договоры'},
        ),
        migrations.AlterModelOptions(
            name='objectbydogovor',
            options={'verbose_name': 'Объект договора', 'verbose_name_plural': 'Объекты договора'},
        ),
        migrations.AddField(
            model_name='objectbydogovor',
            name='sluck',
            field=models.CharField(default=1, max_length=100, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Договор'),
        ),
    ]
